apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: tigercub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: tigercub-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tigera-network-admin
subjects:
- kind: ServiceAccount
  name: tigercub
  namespace: default
---
